CREATE DATABASE dbLogin
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_0900_bin;

USE dbLogin;

CREATE TABLE tblUser(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
usr VARCHAR(45),
pwd VARCHAR(45)
);

INSERT INTO tblUser(usr, pwd) VALUES
('Laura','12345');